# Oops, we forgot to set the sm_app_role variable...
#
# sm_app_role: bar
#
# Since variables are supposed to be scoped to roles, I would expect this output:
#
#   TASK: [bar | print value of sm_app_role] **************************************
#   ok: [localhost] => {
#       "sm_app_role": "{{ sm_app_role }}"
#   }
#
# But instead I get this:
#
#   TASK: [bar | print value of sm_app_role] **************************************
#   ok: [localhost] => {
#       "sm_app_role": "dog"
#   }
#
# The latter seems to suggest that in at least some cases there is leakage of
# variables from one role to another.
